# Generated by Django 5.2.12 on 2026-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='kids_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
