# Generated by Django 5.2.12 on 2026-03-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacher_kids_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='kids_description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
