# Generated by Django 5.2.12 on 2026-03-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_teacher_kids_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.teacher')),
            ],
            options={
                'ordering': ('teacher', 'weekday', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('teacher', 'weekday', 'start_time', 'end_time'), name='uniq_teacher_weekday_time_range')],
            },
        ),
        migrations.CreateModel(
            name='TrialLessonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('teacher_confirmed', 'Teacher confirmed'), ('admin_approved', 'Admin approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('student_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('zoom_join_url_student', models.URLField(blank=True)),
                ('zoom_join_url_teacher', models.URLField(blank=True)),
                ('zoom_start_url_host', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lesson_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lesson_requests', to='api.teacher')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['teacher', 'start_at'], name='api_trialle_teacher_72ee2e_idx'), models.Index(fields=['student', 'status'], name='api_trialle_student_b59d59_idx')],
            },
        ),
    ]
