# Generated by Django 5.2.13 on 2026-04-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacheravailability_triallessonrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheravailability',
            name='end_time',
            field=models.TimeField(help_text='End time of availability window in Pacific Time'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='start_time',
            field=models.TimeField(help_text='Start time of availability window in Pacific Time'),
        ),
    ]
