# Generated by Django 5.2.13 on 2026-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='triallessonrequest',
            name='teacher_note',
            field=models.TextField(blank=True),
        ),
    ]
