# Generated by Django 5.2.12 on 2026-06-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_freeconsultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeconsultationrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
